feat(tests): add test to check tag close kestra-io/helm-charts#194

diff --git a/.github/workflows/helm-tests.yml b/.github/workflows/helm-tests.yml
--- a/.github/workflows/helm-tests.yml
+++ b/.github/workflows/helm-tests.yml
@@ -21,6 +21,20 @@ jobs:
           echo "kubeconform 0.7.0" >> .tool-versions
       - name: Set up ASDF
         uses: asdf-vm/actions/install@v4
+      - name: Check if appVersion image exists
+        id: check_image
+        run: |
+          APP_VERSION=$(grep '^appVersion:' charts/kestra/Chart.yaml | awk '{print $2}' | tr -d '"')
+          echo "Detected appVersion: $APP_VERSION"
+          IMAGE_NAME="kestra/kestra"
+          echo "Checking if image $IMAGE_NAME:$APP_VERSION exists on Docker Hub..."
+          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/${IMAGE_NAME}/tags/${APP_VERSION}/")
+          if [ "$STATUS_CODE" -ne 200 ]; then
+            echo "::error::Docker image ${IMAGE_NAME}:${APP_VERSION} does not exist on Docker Hub."
+            exit 1
+          else
+            echo "Docker image ${IMAGE_NAME}:${APP_VERSION} exists on Docker Hub."
+          fi
       - name: Run tests
         run: |
           helm template charts/kestra -f charts/kestra/values-testing.yaml --validate=false > output.yaml
